### ISSUE TITLE
Change get Version to get Versions

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-API#104]
In order to run multiple BCF-API versions in parallel the v 2.1 should have .../versions, so that .../version in v1 don't have to be changed.

**Comment by jasollien** [comment]
https://github.com/BuildingSMART/BCF-API/pull/106

**Comment by GeorgDangl** [comment]
To clarify: Add `versions` endpoint for BCF API 2.1 and newer -> `version` (singular) will then still be aailable for v1.0 clients

**Comment by jasollien** [comment]
@GeorgDangl: Is the PR ok?

**Comment by GeorgDangl** [comment]
Yeah, looks good!

So, fixed by #106
