### ISSUE TITLE
Remove authoringToolId?

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-API#108]
Are there anyone that actually uses this id?

**Comment by jasollien** [comment]
Bimsync does not

**Comment by ErikPijnenburg** [comment]
BIMcollab and its BCF Managers are not using it.
Real openBIM should rely on open formats so for me it does not belong to BCF.

**Comment by ykulbak** [comment]
AS discussed is https://github.com/buildingSMART/BCF-XML/issues/182 - AuthoringToolId is needed and used.
