### ISSUE TITLE
Viewpoint change merged too soon

### ISSUE THREAD

**Issue by pbuts** [BuildingSMART/BCF-API#113]
[Pull request #103](https://github.com/BuildingSMART/BCF-API/pull/103) is merged too soon.

The minutes of the Telco on 2016-11-28 only mention work on the XML counterpart of this issue and documentation, not that the proposal is accepted as such.

I object to 3 parts of this proposal:

1 The term 'relevant':

When you have a clash viewpoint that has only the two clashing components visible (through the visibility list), those are the relevant components and the 'relevant' list will be empty.

What you now call 'relevant' used to be managed by the 'Selected' attribute. I think in terms of usage this selection should be thought of as a way to higlight the component. Coloring is also a way to make components attract attention, but the highlight should superseed that. So I propose to rename 'relevant' to 'highlight' and leave it up the the client how to visualize this.

2 The Visibility element

It must be clear that the *_on flags are only hints and as such may have no influence on the logic used to create and reproduce viewpoints. That is totally not clear from the location of these properties.

I propose to group them in an object called something like 'ViewSetupHint'. And that object should be a child of the viewpoint object (at the same level as e.g. 'snapshot' and 'components') because it is actually not related to the components.

It should be documented that these are only hints too, but I'm afraid not everyone reads the documentation really well, so better have the schema as self-documenting as possible.

3 Naming consistency
Naming of the 3 sub-objects of components is not consistent. I propose, with back-reference to my first objection:
'highlight', 'color' and  'visibility'

**Comment by GeorgDangl** [comment]
[Please us the issue in the BCF XML repository for discussion.](https://github.com/BuildingSMART/BCF-XML/issues/121)

**Comment by GeorgDangl** [comment]
Closing since it has now been resolved.
