### ISSUE TITLE
Oauth2: The client must know if the server demands client credentials 

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-API#117]
Background: Some servers requires client credentials when serving access_token.

According to the odata2 specification (https://tools.ietf.org/html/rfc6749#section-4.1.3):

"If the client type is confidential or the client was issued client
   credentials (or assigned other authentication requirements), the
   client MUST authenticate with the authorization server as described
   in Section 3.2.1".

From section 3.2.1 (https://tools.ietf.org/html/rfc6749#section-3.2.1):
...
Confidential clients or other clients issued client credentials MUST
   authenticate with the authorization server as described in
   Section 2.3 when making requests to the token endpoint.
...

From section 2.3.1(https://tools.ietf.org/html/rfc6749#section-2.3):
Clients can be authorized in two ways.

By using basic authentication in the header, or by using client_id and client_secret in the body.

My suggestion is:

Auth_GET.json {
    .....
    requiresClientAuthentication: true/false;
}

And here: https://github.com/BuildingSMART/BCF-API#323-oauth2-protocol-flow---token-request
"The POST request can be done via HTTP Basic Authorization with your applications client_id as the username and your client_secret as the password.
" should be changed to: "If the server requires client authentication: Authorize you request via HTTP Basic Authorization with your applications client_id as the username and your client_secret as the password."

**Comment by jasollien** [comment]
@GeorgDangl I read some more in the Oauth2 documentation.

Actually, a server can provide both public and confidential clients. That means that requiresClientAuthentication cannot be a global variable, but is in context of the clientId. I don't actually know how this can be exposed in the API. Perhaps we have to describe this:

Clients can be both confidential and public.
Public clients authenticates with clientId.
Confidential clients authenticats with both clientId and clientSecret

https://tools.ietf.org/html/rfc6749#section-2.1

**Comment by GeorgDangl** [comment]
See #124
