### ISSUE TITLE
Oauth2 flows

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-API#123]
Here is a list of oauth2 flows:
Authorization Code Grant (4.1)
Implicit Grant (4.2)
Resource Owner Password Credentials Grant (4.3)
Client Credentials Grant (4.4)
Extension Grants (4.5)

source: https://tools.ietf.org/html/rfc6749

@GeorgDangl: Could you include a list of these enums in the auth resource?

**Comment by GeorgDangl** [comment]
I'm leaving 4.4 out of the description because it is only about issuing tokens to clients without an user identity, so it's not applicable to the BCF API.

**Comment by GeorgDangl** [comment]
See #124
