### ISSUE TITLE
Paging of topic and comment history

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-API#127]
The structure of Topic Events (And comment events) is

{
    user: user,
    date: date,
    topic_guid: topic_guid,
    actions: [
        {{x number of actions}}
    ]
}

I am wondering how we should treat skip/limit. Should we skip/limit the actions or the events?

From a server perspective, using skip/limit on events would cause bad performance. You must loop over all actions, because you don't know how many actions there may be for each event.

Using skip/limit on actions would cause good performance. However, it might be more complicated for the clients using it, since they cannot be sure that an event contains all actions belonging to it.

I would be happy for any feedback on this

**Comment by GeorgDangl** [comment]
This should be supported via OData parameters
