### ISSUE TITLE
PATCH for partial update of resources

### ISSUE THREAD

**Issue by Wilt** [BuildingSMART/BCF-API#128]
In the PUT example for topic [here](https://github.com/BuildingSMART/BCF-API#424-put-topic-service) all the fields are sent to the BCF server. 

`````
PUT /bcf/2.1/projects/F445F4F2-4D02-4B2A-B612-5E456BEF9137/topics/B345F4F2-3A04-B43B-A713-5E456BEF8228
Body:
{
    "topic_type": "Clash",
    "topic_status": "open",
    "title": "Example topic 3 - Changed Title",
    "priority": "high",
    "labels": [
        "Architecture",
        "Heating"
    ],
    "assigned_to": "harry.muster@example.com",
    "bim_snippet": {
        "snippet_type": "clash",
        "is_external": true,
        "reference": "https://example.com/bcf/1.0/ADFE23AA11BCFF444122BB",
        "reference_schema": "https://example.com/bcf/1.0/clash.xsd"
    }
}
`````

Are there any future plans for supporting PATCH operations for only editing some of the fields? For example to change the status of a issue it would in such case be possible to only send one field:

`````
PATCH /bcf/2.1/projects/F445F4F2-4D02-4B2A-B612-5E456BEF9137/topics/B345F4F2-3A04-B43B-A713-5E456BEF8228
Body:
{
    "topic_status": "open",
}
`````

This would decrease the payload and would allow a different user interface (simpler) on BCF clients .

**Comment by GeorgDangl** [comment]
Http PATCH was included in version 1.0, but we deliberately did not include it for the current version to keep the API specification short and simple.

**Comment by Wilt** [comment]
Any changes of adding this in near future? Especially since the functionality is already available it is a pity that it isn't possible to use it...

**Comment by stardotbmp** [comment]
@Wilt Any implementation of the spec which also included PATCH would not be non-compliant, it just would not specify the expected results. You can read a lot in between the lines and your assumptions for what PATCH would do are likely to be correct.

**Comment by GeorgDangl** [comment]
We've talked about this again in the last BCF telecon and decided that for now, we'll stick to only specifying `PUT` in the documentation since it's making implementations easier and the larger payload size should be handleable.
