### ISSUE TITLE
[Release 1.0] File services : all fields can be null ?

### ISSUE THREAD

**Issue by bat79a** [BuildingSMART/BCF-API#131]
For the file services model all fields can be null ?
One field must be required no ? 

May be this two fileds : ifc_project, file_name ?

**Comment by GeorgDangl** [comment]
That's again coming from the [BCF XML 2.0 schema](https://github.com/BuildingSMART/BCF-XML/blob/release_2_0/Schemas/markup.xsd#L17-L27).
I'm not sure what's the exact reason behind that, but it would be safe to assume that a `file` is only exported when there's meaningful information in it.
