### ISSUE TITLE
[Release 1.0] Clipping_planes and lines are not an Array ?

### ISSUE THREAD

**Issue by bat79a** [BuildingSMART/BCF-API#132]
For clipping_planes and lines I think that they must be an array and not a field with an array inside.

Actual field : 
```
clipping_planes : {
  clipping_plane: []
}
```

Must be : 
Actual field : 
```
clipping_planes : [
]
```

**Comment by GeorgDangl** [comment]
That's also a result of a direct mapping from BCF XML 2.0 to BCF API 1.0. It's not beautiful, but functionally equivalent. It's been taken care of in versions 2.1.

**Comment by bat79a** [comment]
So that in 2.1, just better ;p

**Comment by bat79a** [comment]
LOL
