### ISSUE TITLE
[Release 1.0] Viewpoint Bitmap is an integer or a string ?

### ISSUE THREAD

**Issue by bat79a** [BuildingSMART/BCF-API#133]
The text documentation said that the viewpoint bitmap is a enum string, but json said that is an integer enum ?

text : 
```
enum	string	Format of the bitmap. Predefined values "png", "jpg", "bmp"
```

json : 
```
"bitmap": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "bitmap": {
          "type": "integer",
          "enum": [
            0,
            1,
            2
          ],
```

**Comment by GeorgDangl** [comment]
There's an `options` field that [explains the values](https://github.com/BuildingSMART/BCF-API/blob/v1.0/Schemas_draft-03/Collaboration/Viewpoint/viewpoint_GET.json#L252-L274). It's the result of  when we used C# classes (where enums are integers internally) to generate the schemas.

**Comment by bat79a** [comment]
Okayyyy ;p 
Thx a lot for your explanation

I saw that the 2.1 release is a string type.
