### ISSUE TITLE
[Release 1.0] Component model all fields can bu null ?

### ISSUE THREAD

**Issue by bat79a** [BuildingSMART/BCF-API#134]
For the component model I think that the field ifc_guid must be required ?

**Comment by GeorgDangl** [comment]
It could be null if the component only has an internal identifier specific to a CAD system but no IFC representation yet.

**Comment by bat79a** [comment]
Ok so one of the two field must be required by json validators or UI if I understand ?

If ifc_guid is empty authoring_tool_id must be required ? and vice versa.

**Comment by GeorgDangl** [comment]
I don't think that's explicitly stated somewhere in the specification, so it's not a hard requirement. But if a `component` has no relation to any model object then I would just ignore it.

**Comment by bat79a** [comment]
yep, but the database will have unnecessary records ! so bad ;p
