### ISSUE TITLE
Separation beteween internal and external documents in 2.1 is not possible

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-API#141]
In the documentation for BCF-API v1 it was clearified that a document reference guid points to the internale document. In documentation for v2.1 this is not clearified.

The problem. It is impossible for the client to know if a document reference points to an internal document or is external. The only way is to trigger getDocument(guid) and check if you get "Not Found" or not. Not good practise.

This fix clearly separates these two values. External document reference uses url, while internal document reference uses document_guid.

I have also interpreted that guid on a document_reference should be the guid for the document_reference, not for the document.

Therefore, when using PUT, the guid should be mandatory (Update of an existing document reference)

There should also be a DELETE method that removes a document_reference.

https://github.com/BuildingSMART/BCF-API#472-post-document-reference-service

**Comment by GeorgDangl** [comment]
This is already fixed
