### ISSUE TITLE
Documents and files needs a timestamp

### ISSUE THREAD

**Issue by lbj** [buildingSMART/BCF-API#142]
I assume that files are any IFC files relevant for a BCF api session while documents are any other document or file related to topics. There is currently no good explanation for the difference in the documentation.

Files and documents are useful concepts in BCF but it doesn't seem to be any way to know when a document or file is updated on a server. In effect a client would have to always download everything in order to assure that the most recent version is downloaded. A timestamps on these resources would resolve the problem.
Files are also missing unique identifiers something that is needed when used on a bimserver with multiple models and revisions of ifc files. If files had both a time-stamp and guid a client (for example a CAD tool) could use the BCF api to always keep referenced IFC files in sync for a project.

**Comment by GeorgDangl** [comment]
Tracked in #181
