### ISSUE TITLE
Cannot expose file download url without any kind of authentication

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-API#143]
The topic files service returns a list of related models for that topic.

Each file contains a reference, which should be the download url for the model file.

In bimsync, we can expose a download url for the model, but we cannot allow non authenticated requests in the download service.

Solution 1: Expose url to the web application, which requires the user to be signed in. (Not ideal if the client want to download the file directly)

Solution 2: Instead of exposing the reference to the download url, expose an ID to the file. The download service must be a part of the BCF API standard, and requests can be authenticated using the access token.

Suggested fileGET response:
{
    "ifc_project": "0J$yPqHBD12v72y4qF6XcD",
    "file_name": "OfficeBuilding_Architecture_0001.ifc",
    "file_guid": {file_guid}
}

Suggested download url:
/projects/{project}/topics/{topic}/files/{file_guid}

**Comment by GeorgDangl** [comment]
This is now part of the docs:
https://github.com/BuildingSMART/BCF-API#431-get-files-header-service
