### ISSUE TITLE
Specify best practise for topic and comment events in documentation

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-API#144]
Comment and topic initial state may be lost from history in event services

Example:

A topic with a text is created.
A created event is generated on the server.

The title of the topic is updated
A title_updated event is generated on the server, with the new title as value

However, the initial topic title is lost from the history.

Therfore:
The documentation should specify that "updated" events should also be triggered when "first" created.

Example:
A title_updated event should be generated when a topic has been created.

**Comment by GeorgDangl** [comment]
We've included an updated description in sections 4.9 and 4.10
