### ISSUE TITLE
Add HATEOAS self:links in resource schemas?

### ISSUE THREAD

**Issue by stardotbmp** [BuildingSMART/BCF-API#147]
Implementing HATEOS reference links to resources would be a key part of the RESTful server. Would it be therefore a point to add these to the Schemas?

[Wikipedia: HATEOAS](https://en.wikipedia.org/wiki/HATEOAS)

```
GET /bcf/projects
[
  {
    "project_id": "7d7953eb-de34-96a3-19fc-2b9321e44a2f"
    "name": "Big Project",
    "links": [ {
        "rel": "self",
        "href": "http://{server}/bcf/projects/7d7953eb-de34-96a3-19fc-2b9321e44a2f"
    } ]
  },
  {
    "project_id": "59685e17-8c25-4b11-ad5f-f3e507f9bba6"
    "name": "Baby Project",
    "links": [ {
        "rel": "self",
        "href": "http://{server}/bcf/projects/59685e17-8c25-4b11-ad5f-f3e507f9bba6"
    } ]
  },
]
```

or a more concise form

```
GET /bcf/projects
[
  {
    "project_id": "7d7953eb-de34-96a3-19fc-2b9321e44a2f"
    "name": "Big Project",
    "self": "http://{server}/bcf/projects/7d7953eb-de34-96a3-19fc-2b9321e44a2f"
  }
]
```

**Comment by GeorgDangl** [comment]
Hi Jonathan,

I think this was at one time already discussed, I'll check the minutes of the BCF Implementers Group for that and see what the conclusion was.
The wiki article you refer to mentions that HATEOAS is in contrast to APIs that _...interact through a fixed interface shared through documentation..._, so how would the BCF API benefit from going full self-documenting? I can see a use case that would indicate allowed actions, but this is already covered by the BCF API 2.1 spec in [Authorization](https://github.com/BuildingSMART/BCF-API#18-authorization).

**Comment by stardotbmp** [comment]
Its not essential just good practice.

**Comment by GeorgDangl** [comment]
Hi Jonathon,

we've discussed the issue today in the BCF Implementers telecon. While we agree that this would be best practice, we feel it's not currently necessary and introducing it would make not benefit consumers of the API.

By the way, you're welcome to join the BCF Implementers call if you want. We're usually having a call every two weeks on Monday, 11:00 AM CET.
