### ISSUE TITLE
The "short form URLs" doesn't work in projects that also uses BCF file import 

### ISSUE THREAD

**Issue by lbj** [BuildingSMART/BCF-API#15]
In order to support a /topic/ URL on root, we would have to prevent topics from sharing the same Issue GUID between projects. This is not always the case. We see examples where the same BCF file is imported in different projects, and in my opinion a BCF server with an API should also optionally support BCF file imports. I suggest removing this URL and use the version including the ProjectId instead for example (GET /bcf/{version}/projects/{guid}/topics/{guid}) instead of GET /bcf/{version}/topics/{guid}

If we intend to support scenarios where users can import BCF files as well as using the API, we will have to remove the following URLs:

GET /bcf/{version}/topics/{guid}
PUT /bcf/{version}/topics/{guid}
GET /bcf/{version}/topics/{guid}/snippet
PUT /bcf/{version}/topics/{guid}/snippet
GET /bcf/{version}/topics/{guid}/files
PUT /bcf/{version}/topics/{guid}/files
GET /bcf/{version}/topics/{guid}/comments
POST /bcf/{version}/topics/{guid}/comments
GET /bcf/{version}/comments/{guid}
PUT /bcf/{version}/comments/{guid}
GET /bcf/{version}/topics/{guid}/viewpoints
POST /bcf/{version}/topics/{guid}/viewpoints
GET /bcf/{version}/viewpoints/{guid}
PUT /bcf/{version}/viewpoints/{guid}
GET /bcf/{version}/viewpoints/{guid}/snapshot
PUT /bcf/{version}/viewpoints/{guid}/snapshot
GET /bcf/{version}/viewpoints/{guid}/components
POST /bcf/{version}/viewpoints/{guid}/components
GET /bcf/{version}/topics/{guid}/related_topics
POST /bcf/{version}/topics/{guid}/related_topics
GET /bcf/{version}/topics/{guid}/document_references
POST /bcf/{version}/topics/{guid}/document_references

**Comment by GeorgDangl** [comment]
Hi lbj,

could you give an example where the same BCF Topic would be imported into different projects? Guids were chosen to be globally unique, so in practice there should never be two topics that share the same guid.

**Comment by lbj** [comment]
Hi @GeorgDangl 

Yes. While GUIDs are unique by nature there is nothing that prevents, or should prevent two users from uploading or checking in the same BCF issues in two different projects. One typical use-case is where a group of students work with a set of predifined ifc and bcf files in education. I assume we want to keep the original GUID for issues from bcf2.0 files upon import.

~Lars

**Comment by GeorgDangl** [comment]
Hi @lbj,

if duplicated Guids would be possible, then we would clearly have to state this in the documentation. A BCF client with local caching could get confused when it connects to a server and receives different topics with the same Guid. You would also need to create a new, artificial ID for, p.e., database storage and it would break existing implementations. Guids would then no longer be the identifier for an object as they are now.

**Comment by teocomi** [comment]
IMHO, if the same BCF issue can be uploaded to different projects then it should share the same information, comments and views. I don't think there should be BCF issues with the same GUID but different data, otherwise the real BCF GUID becomes just a combination of the [projectGUID]+[issueGUID].

Either we approach this project-issue relationship as a taxonomy (the project is like a category/label assigned to the issue) or as a more classical parent-child relationship (like in most issue tracking systems)...

**Comment by lbj** [comment]
The problem here is that a function like GET /bcf/{version}/topics/{guid} assumes that there is only one issue with that {guid} on a BCF/model server. Even if we can limit the possible projects from the authenticated user there is still no guaranty that the given user doesn't have access to two projects where the same issue has been uploaded. The solution is to use the : GET /bcf/{version}/projects/{guid}/topics/{guid}) function instead. 

I'm not suggesting that one project should allow for several identical issue_guids. I'm just suggesting that you could have issues with identical GUIDs stored in different projects. Just like you will have the same ifc file uploaded to different projects on a modelserver. 
So my suggestion is simply to remove the URLs missing the /projects/{guid}/ bit, from the documentation. 

For example for : 

4.2.3 GET Single Topic Services

Recource URL
 **GET /bcf/{version}/topics/{guid}**
 GET /bcf/{version}/projects/{guid}/topics/{guid}

We remove the line in **bold**

**Comment by linhard** [comment]
Has been taken care of.
