### ISSUE TITLE
JSON-schema hyperlinks for v1 of the API points to master branch, not to release v1

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-API#150]

**Comment by jasollien** [comment]
After investigation a bit more, I think the real problem is that the tag v1.0 is not the same as the branch relase_1_0. The json hyperlinks works fine in the branch release_1_0, but not in the tag v1.0

**Comment by jasollien** [comment]
@GeorgDangl, I ended up concluding with the same as the last comment on 27. sep. Can you change the "tag" v.1.0, so that it points to the branch "release_1_0"? That will fix the issue

**Comment by GeorgDangl** [comment]
It looks like there's not an easy way to just move the v1.0 tag to another branch, I fear this might break something from the releases maybe.
@jasollien, could you point me to where the invalid link is? I couldn't find it.

**Comment by ykulbak** [comment]
Closing since we couldn't move the tag and also because most (if not all) of the API implementations support BCF API 2.1
