### ISSUE TITLE
odata filter example is wrong

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-API#154]
Look at this example. "status" should be "topic_status"

GET /bcf/2.1/projects/F445F4F2-4D02-4B2A-B612-5E456BEF9137/topics?$filter=assigned_to eq 'Architect@example.com' and status eq 'Open' and creation_date gt 2015-12-05T00:00:00+01:00&$orderby=modified_date desc

Fixed here: https://github.com/BuildingSMART/BCF-API/pull/153

**Comment by GeorgDangl** [comment]
Thanks!

Fixed in #153
