### ISSUE TITLE
Web Example of IFC file

### ISSUE THREAD

**Issue by krosoftware** [BuildingSMART/BCF-API#156]
Hello 
is there any example of how to use API to view and get values from IFC file, please?
Thank you.

**Comment by GeorgDangl** [comment]
Hi kro,

the BCF API itself is not a BIM or a Model API itself. That means it doesn't specifiy ways to access model data itself.

There are, however, features to link issues and models. One would be the [File Services](https://github.com/BuildingSMART/BCF-API#43-file-services), to link specific IFC files to topics. The other, [Viewpoint Services](https://github.com/BuildingSMART/BCF-API#45-viewpoint-services) is for model information related to an issue, e.g. selected components or viewer settings.

**Comment by krosoftware** [comment]
Hello
OK could you please tell me is it possible to create software which will display specific IFC file in the web-browser and to interact with the clicked objects using events?
If yes, I'm interested and please tell me about price. You can contact me by email.
Thank you.

**Comment by GeorgDangl** [comment]
Hi kro,

there absolutely is software to do that. For example, [I've set up a demo](https://xbim-web.dangl.me/home) that's using the open source xBim libraries in an Asp.Net Core backend to convert and display IFC files in an Angular frontend. [I've made the source code available for the demo on GitHub](https://github.com/GeorgDangl/xbim-meets-angular).

I'm marking this issue as resolved, please just reply if I should reopen it.
