### ISSUE TITLE
OpenAPI as description format?

### ISSUE THREAD

**Issue by bufferoverflow** [BuildingSMART/BCF-API#157]
I suggest to use the OpenAPI (aka swagger) format as API description, this allows people to generate clients and servers very easily and it is widely used, see:

- https://www.openapis.org/
- https://editor.swagger.io/

**Comment by GeorgDangl** [comment]
Hey @bufferoverflow, thanks for you input!

We've had the BCF Winter Hackathon last week in Munich where we also talked about using Swagger / OpenAPI as API description format, but decided not to create it as part of this repository for now.
As we see it, OpenAPI is a great tool to formally describe APIs, but we believe that for an API specification that is implemented both by various clients and servers, we want to stick to the format we currently use with all it's explanations, conventions and examples.

However, we'd appreciate and welcome any contribution in that matter!
