### ISSUE TITLE
ViewSetupHints

### ISSUE THREAD

**Issue by KevLoh** [buildingSMART/BCF-API#164]
XML and API specifications differ for ViewSetupHints:

XML - https://github.com/BuildingSMART/BCF-XML/blob/release_2_1/Schemas/visinfo.xsd :

      <xs:complexType name="Components">
		<xs:sequence>
			<xs:element name="ViewSetupHints" type="ViewSetupHints" minOccurs="0" />
			
			<xs:element name="Selection" type="ComponentSelection" minOccurs="0" />
			<xs:element name="Visibility" type="ComponentVisibility" minOccurs="1" />
			<xs:element name="Coloring" type="ComponentColoring" minOccurs="0" />
		</xs:sequence>
     </xs:complexType>

API: https://github.com/BuildingSMART/BCF-API#452-post-viewpoint-service
**4.5.2.12 Visibility** (not possible to link)
![grafik](https://user-images.githubusercontent.com/23518055/38551015-5dc2a376-3cb8-11e8-835d-5fe5304eeb46.png)

We need to unify both specification!

**Comment by GeorgDangl** [comment]
In the API, `view_setup_hints` is inside `visibility`, while in XML it's on the same level as `Visibility`.

**Comment by jasollien** [comment]
Ah, right. It shoud be inside visibility in the XML as well

**Comment by jasollien** [comment]
Closing since the API is correct

**Comment by Wilt** [comment]
I am surprised this issue is closed.
Why not make the structure for XML and json views match? 
What if someone gets a view as json and later converts it to XML and tries to load it?
Would it be a problem to make the API consistent for different file types?
