### ISSUE TITLE
POST Document Service need header?

### ISSUE THREAD

**Issue by KevLoh** [BuildingSMART/BCF-API#170]
Documentation for v2.1 does not give any hints about header details:
https://github.com/BuildingSMART/BCF-API#482-post-document-service

For v1.0, there are requirements for the header:
https://github.com/BuildingSMART/BCF-API/tree/release_1_0#492-post-document-services

At least BimSync do require the headers to be present.

-> Missing documentation?

**Comment by GeorgDangl** [comment]
Hi @KevLoh, thanks for raising this!

I've digged a bit and found it was removed in 25dfd4818a6ec1b0fc4853cea7e2696a772d5afb.
The minutes from the BCF call say:
**BCF API Issues**
Currently open issues on GitHub have been discussed and the following actions have been decided
* Issue #52 – Response codes in examples
    Decided to include the expected Http response codes in the response examples. **Headers will not be explicitly mentioned in the specification and will be removed** where they are now

The thing is, why did we do this...

I _think_ we meant that in the BCF API, files are uploaded as streams, not as, for example, `multipart/form-data` requests. We should probably write this down somewhere in the introduction.
