### ISSUE TITLE
No POST Project url in the doc ?

### ISSUE THREAD

**Issue by bat79a** [BuildingSMART/BCF-API#176]
Hi.

In the documentation there is no POST method for create a new project ?

**Only GET and PUT method :** 
4. BCF Services
4.1 Project Services
4.1.1 GET Projects Service
4.1.2 GET Project Service
4.1.3 PUT Project Service

Thx.

**Comment by GeorgDangl** [comment]
Hey Baptiste,

that's correct, there's no `POST` method to create projects via the BCF API.
It was originally specified in version 1.0 of the API, but we decided to drop it.

The reasoning behind that decision was that all servers that do support the BCF API usually have some kind of UI or project management system already, so creating projects should usually be done in the original system before external users are connecting via the API. Also, most servers require some additional project setup, so a simple `POST Project` would often not have been enough and required configuration in the native system anyways.
