### ISSUE TITLE
"filename" and "file_name" inconsistency

### ISSUE THREAD

**Issue by nicktindall** [buildingSMART/BCF-API#177]
In the header "files" endpoints the file name property is "file_name" but in the documents API endpoints the file name is "filename".

Not a big deal, but it should probably be consistent. I find it hard to have an opinion on which is correct.

**Comment by ykulbak** [comment]
@nicktindall can you please offer a pull request ;-)

**Comment by ykulbak** [comment]
Thanks @nicktindall !!
