### ISSUE TITLE
Suggestion to usage of extension recources

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-API#18]
Hi

We would like to implement the extension POST/PUT method, but it does not seem to fit our needs.

From documentation the only way to change an extension scheme is by passing in the entire schema. This makes it unclear, what will actually happen with the existing schema values.

For example:
Let's say I would like to rename the status "review" to "under concideration". By using the extension POST method, you must get the current schema, rename the status and pass the schema back.

How should the server handle this? It can assume that "review" was removed and "under concideration" was added, and therefore assume it was a rename, but that is not good practice.

My suggestion would be the following:
1. Remove extension schema POST/PUT resources
2. Create "POST, PUT, DELETE" resources for statuses, types, priorities etc...

Thanks for feedback

**Comment by GeorgDangl** [comment]
Decision to not go on with this.

Extension POST and PUT will be removed from the services for V2.1 since this should be handled in the native environments.
