### ISSUE TITLE
All resources should have timestamps and author information

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/BCF-API#181]
Something like the following properties should be part of all entities that can be created by users:  
`created_by`, `created_at`, `modified_by`, `modified_at`

This should at least cover the following resources: Projects, Topics, Comments, Viewpoints, Documents and Files.

This issue unifies both #163 and #142.

**Comment by KevLoh** [comment]
From #163 :
Additionally, @KevLoh from DDS mentioned that we should also include viewpoint creation in the events. We only need a created event, since per the specification, viewpoints should be immutable.

**Comment by GeorgDangl** [comment]
[2021-09-30 bSGer-IDM_BCF_EN.pdf](https://github.com/buildingSMART/BCF-API/files/10956181/2021-09-30.bSGer-IDM_BCF_EN.pdf)

Here's a paper from the BCF Stuttgart Group @pkoska

**Comment by GeorgDangl** [comment]
We need to discuss if documents and files are required, or if we might even remove them. But the modified and created properties should be present and mandatory for the other resources.

**Comment by GeorgDangl** [comment]
See #292 for viewpoints

**Comment by GeorgDangl** [comment]
There's an open PR for viewpoints.

For projects, we've decided to not include it, since author information might not always either be present or be relevant there.

For files, it's similar. We've decided not to include author / audit information there. Servers may fill the display properties for files, though, to show e.g. creation dates and author names.
