### ISSUE TITLE
Typo in BCF-API README example request of the POST Viewpont Service

### ISSUE THREAD

**Issue by KreuzigTobias** [buildingSMART/BCF-API#184]
In the example request body of:
https://github.com/buildingSMART/BCF-API#452-post-viewpoint-service there is a typo in the components>"visibility">"default_visbility"

It should be default_visibility 
,I search for hours why it didn't work, and changing it shouldn't take more than 5 mins.

Thanks

**Comment by ykulbak** [comment]
The issue seems to have been fixed - the typo can no longer be found.

**Comment by CBenghi** [comment]
Yes, I think it was fixed in cd0f8e2a81674ebe2dd5132435dbd86091e0c72a
