### ISSUE TITLE
Specifiy default limits for pagination of list resources

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/BCF-API#187]
Jon Anders Sollien just raised an issue in the telecon where some clients don't honor paginated results for list resources.
In their case, they were using default page sizes. If clients accessed list resources with more entries than the default page size, the clients didn't fetch the second page, leading to users missing data.

Steps to resolve:

* A default page size should be used by servers, possible directly specified by the BCF API specification
* Clients should honor this limit. For example, if a response contains exactly the amount of items as the default page size, clients can send another request to fetch the next page to check if there are more items available

We'd be happy to get some more feedback on this issue.

**Comment by KevLoh** [comment]
In DDS-CAD we are not doing any pagination at the moment. 

E.g. we interprete 'Get Topics' service to get **all** topics. But we do see the need for updating something.

I kind of disagree to second bullet point. Clients IMHO should NOT send a second request just out of better knowledge. What if there are exactly the amount of topics the server has as its limit?

Wouldn't it be better, if the server would indicate,
- the actual number of topics the client could get and it's page size **OR**
- if there are more topics to retrieve.

This should be done for **all** items that can be retrieved. So I assume we should have several page size values.

**Comment by GeorgDangl** [comment]
As discussed on the hackathon, this should be resolved in a future version by introducing some kind of wrapper item for list responses that includes additional data like `currentPage`, `totalPages`, `totalItems` or similar.

**Comment by GeorgDangl** [comment]
We haven't encountered any issues with pagination in the recent versions, so we've decided in the call to close it for now. We may revisit pagination later if issues do appear.
