### ISSUE TITLE
Remove Status and VerbalStatus from Comment

### ISSUE THREAD

**Issue by pasi-paasiala** [BuildingSMART/BCF-API#19]
Status and VerbalStatus are phased out in BCF-XML. I think we shouldn't have them in BCF-API. See here the reference to BCF-XML documentation: https://github.com/BuildingSMART/BCF-XML/tree/master/Documentation#status-and-verbalstatus-to-be-phased-out.

**Comment by GeorgDangl** [comment]
See Pull Request #41 for the changes.

**Comment by lbj** [comment]
Phasing out status and verbal_status on comments is fine as long as BCF provides an alternative solution for handling issue history. A server receiving BCF files with more than one comment will have no clue about the original state of the issue, who changed the status or when. This change renders BCF 2.1 rather useless as basis for a file based BCF exchange or for transferring history between BCF servers. I cannot see how removing the only existing way of handling history in BCF will benefit BCF in any way.
