### ISSUE TITLE
Example URL for getting colored components is wrong

### ISSUE THREAD

**Issue by KevLoh** [buildingSMART/BCF-API#191]
Copy & paste issue?

https://github.com/BuildingSMART/BCF-API#457-get-colored-components-service

> GET /bcf/2.1/projects/F445F4F2-4D02-4B2A-B612-5E456BEF9137/topics/B345F4F2-3A04-B43B-A713-5E456BEF8228/viewpoints/a11a82e7-e66c-34b4-ada1-5846abf39133/selection

**Comment by GeorgDangl** [comment]
Thank you for finding that, it's fixed in 6364007!
