### ISSUE TITLE
Bitmap question

### ISSUE THREAD

**Issue by Gmacko** [buildingSMART/BCF-API#203]
Hi everyone,

After reading the documentation on the API ([4.5.2.7 Bitmap](https://github.com/buildingSMART/BCF-API#4527-bitmap)), i don't understand what is a bitmap on the viewpoint and why a viewpoint can have more than one bitmap. 

I don't know if i miss an another documentation who explain what is a bitmap.

I just want to know if a bitmap is integral to the snapshot of the viewpoint, or if he's just a preview of the snapshot or if he's another thing ?

Thanks for your replies.

**Comment by mattikannala** [comment]
"A list of bitmaps can be used to add more information, for example, text in the visualization. It has the following elements:"

![image](https://user-images.githubusercontent.com/47979460/96224375-27140080-0f98-11eb-879b-4d30a32e7018.png)

https://github.com/BuildingSMART/BCF-XML/tree/master/Documentation#bitmap-optional

"Lines can be used to add markup in 3D. Each line is defined by three dimensional Start Point and End Point. Lines that have the same start and end points are to be considered points and may be displayed accordingly."
https://github.com/BuildingSMART/BCF-XML/tree/master/Documentation#lines-optional

**Comment by Gmacko** [comment]
Thanks for your reply.
