### ISSUE TITLE
ifcGuid is specified as "optional" in BCF-API documentation

### ISSUE THREAD

**Issue by rahulsule** [buildingSMART/BCF-API#205]
This page Component specification in BCF-API specifies ifcGuid as optional whereas BCF-XML documentation specifies it as mandatory.

**Comment by ykulbak** [comment]
Resolve in a manner consistent with https://github.com/buildingSMART/BCF-XML/pull/228

**Comment by leosobral** [comment]
Discussed in BCF hackathon and agree to improve the doc of BCF-API, I will provide a PR

**Comment by leosobral** [comment]
PR: https://github.com/buildingSMART/BCF-API/pull/256

**Comment by ykulbak** [comment]
Closed by #256
