### ISSUE TITLE
Wrong example request with OData

### ISSUE THREAD

**Issue by Noushed** [buildingSMART/BCF-API#207]
In https://github.com/buildingSMART/BCF-API#42-topic-services , the example shows 
`GET /bcf/1.0/projects/F445F4F2-4D02-4B2A-B612-5E456BEF9137/topics?$filter=contains(labels, 'Architecture') or contains(labels, 'Structural') or contains(labels, 'Heating')`

In OData 4 specification, contains should be used for checking the substring containment. 

http://docs.oasis-open.org/odata/odata/v4.0/os/part2-url-conventions/odata-v4.0-os-part2-url-conventions.html#_Toc372793815

This issue brought up by BIMcollab, and they are proposing as example,
/topics/?$filter=labels/any(label: label eq 'Architecture') or labels/any(label: label eq 'Structural') or labels/any(label: label eq 'Heating’)

**Comment by ykulbak** [comment]
I'm a very small expert with ODATA but based on reading the documentation I think the 'contains' operator was confused with the 'in' operator. The example can also be corrected by:

```GET /bcf/2.2/projects/F445F4F2-4D02-4B2A-B612-5E456BEF9137/topics?$filter=labels in ('Architecture', 'Structural', 'Heating')```

**Comment by ykulbak** [comment]
@Noushed can you please provide a pull request to rectify this issue

**Comment by ykulbak** [comment]
Fixed by #210
