### ISSUE TITLE
Clarify the workflow for Topic Modification date upon Comment modification

### ISSUE THREAD

**Issue by Noushed** [buildingSMART/BCF-API#211]
**In order to** be in a common ground
**As a** Client
**I want** a proper documentation on how we should handle the Topic modification date upon comment modification

#### Acceptance Criteria

- [ ] A clear documentation added for how the server and client will handle the Topic modification date upon Comment modification/addition

#### Info
Question:
Is it an expected workflow to update the Topic modification date when a new comment is added or an existing comment has been updated? 

I would prefer that servers update the Topic modification date upon Comment update. Currently some servers already do that as example Bimsync, BIMTrack etc.

But this question came up because BIMcollab does not update the Topic modification date upon comment modification. And they have also words against updating the topic modification upon comment Modification/addition. 

Currently solibri uses the Topic modification date to recognise the update of Topic in server side. But if any server does not modify the Topic MD upon properties modification which are referring the topic, then there is no way other than calling those property separately and matching with the existing one in client side, which is not an idle way to go for and is also a time/resource consuming call.

**Comment by pbuts** [comment]
We, BIMcollab, indeed hold the position that topic MD should not be linked to comment MD. For us comments support a discussion about the topic and new or modified comments therefore do not change the topic itself and thus also not the topic MD.

We also recognized that for change detection of topics including the discussion, retrieving all comments is not a viable solution: it just takes too much time. Therefore, we added a property to the topic in our extension of the BCF-API that hold the topic's overall MD (= latest of topic MD or any comment MD)

**Comment by ykulbak** [comment]
In the meeting today we agreed that a clarification should be added to the documentation to say that the server's topic modification time should be the latest value of either when the topic was updated or when the latest comment was updated. 

@Noushed can you please create a pull request for this issue.

**Comment by ykulbak** [comment]
@pbuts please confirm that the topic is considered modified also when a "floating viewpoint" (meaning a viewpoint not attached to a comment) is added.

**Comment by leosobral** [comment]
PR: https://github.com/buildingSMART/BCF-API/pull/254

**Comment by ykulbak** [comment]
Closed by #241
