### ISSUE TITLE
Clarify GET Topic - field authorization.topic_status values

### ISSUE THREAD

**Issue by dirkharbinson** [buildingSMART/BCF-API#213]
When returning status values that a topic can be set to, for example a topic that is currently CLOSED and the domain rules say you can OPEN from that state.

1. Should the topic_status values return both OPEN and CLOSED (all transitions including the current state)  
or 
2. Should the topic_status values return only OPEN.

Currently we are assuming that the answer is 1 and you return all possible values you can send through the API (even if that value means no change)

<img width="308" alt="topic authorization" src="https://user-images.githubusercontent.com/6855986/89370700-be511200-d724-11ea-8225-3f2b7c459115.png">

https://github.com/buildingSMART/BCF-API#182-determining-authorized-entity-actions

**Comment by ykulbak** [comment]
Closed with the above merge request
