### ISSUE TITLE
Allow Clients to show custom Topic Properties

### ISSUE THREAD

**Issue by Noushed** [buildingSMART/BCF-API#219]
**In order to** help users to make full usage of Different Server
**As a** Client
**I want** a way to show the Custom Topic Properties and make it usable

#### Acceptance Criteria

- [ ] Custom Topic properties similar as Topic Status/Type can be added
- [ ] If Custom Topic properties is not an accepted idea then document why it is not so that we can refer to our users with proper documentation

#### Info
Currently Several servers supports custom properties (as Example "Area" by BIMcollab). And users are frequently using those options. But From clients side it is not possible to show them to work with. We are frequently getting request regarding that and our answer is always that it is not supported by BCF API.

**Comment by pasi-paasiala** [comment]
@jasollien This is something that you wanted to have.

**Comment by pasi-paasiala** [comment]
This is related to: https://github.com/buildingSMART/BCF-XML/issues/161

**Comment by Noushed** [comment]
There is also an old PR opened by @jasollien https://github.com/buildingSMART/BCF-API/pull/84

**Comment by pasi-paasiala** [comment]
> There is also an old PR opened by @jasollien #84

We don't want to implement a single property.

**Comment by Noushed** [comment]
> > There is also an old PR opened by @jasollien #84
> 
> We don't want to implement a single property.

Yes. Just linked so that we can close that PR upon decision

**Comment by jasollien** [comment]
Can I get your feedback on this? https://github.com/buildingSMART/BCF-API/pull/222

**Comment by GeorgDangl** [comment]
Implemented via #222
