### ISSUE TITLE
Clarify Orthogonal camera view_to_world_scale and Perspective camera field_of_view

### ISSUE THREAD

**Issue by mattikannala** [buildingSMART/BCF-API#226]
Clarify Orthogonal camera view_to_world_scale and Perspective camera field_of_view.
Currently the camera attributes are not clearly specified. They can be implemented based on view width (X) or view height (Y).
The camera attributes must be clearly specified in the documentation.

- [Orthogonal camera view_to_world_scale ](https://github.com/BuildingSMART/BCF-API#4523-orthogonal-camera)
- [Perspective camera field_of_view](https://github.com/BuildingSMART/BCF-API#4524-perspective-camera)

OpenGL uses Y based field of view to create frustum:
https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/gluPerspective.xml

The befefit in Y based field of view and view_to_world_scale is that the 3D objects look the same size in 3D view independent of the 3D view. In many user interfaces the 3D and other UI components are side by side. The user can change the width of the 3D view any time.

Solibri BCF implementation is based on view height (Y) on both Orthogonal and Perspective camera.

**Comment by GeorgDangl** [comment]
See also this issue in the BCF XML repo:
https://github.com/buildingSMART/BCF-XML/issues/175

**Comment by ykulbak** [comment]
Closed by #248
