### ISSUE TITLE
Clarify Viewpoint mandatory and optional fields

### ISSUE THREAD

**Issue by ykulbak** [buildingSMART/BCF-API#227]
This issue is submitted as a result of my attempt to make a respective API change for the clarification in https://github.com/buildingSMART/BCF-XML/issues/199 that when visualisation info is provided then one of orthogonal or perspective camera must be provided. 

The specification in its current form specifies all the viewpoint parameters as optional. This allows inconsistent viewpoints such as viewpoints with clipping plans or selected objects but with no camera. It also allows for viewpoints to be provided that have no information (no camera and no snapshot) except the Viewpoint ID. 

I suggest clarifying that
1.  A view point must contain visualisation information, a snapshot or both
2.  When visualisation information is provided then one of orthogonal or perspective (but not both) must be provided

**Comment by KevLoh** [comment]
Jozsef and I agree :-) 
Guid shouldn't be optional, right?

Not able to merge (missing right access?) :-(

**Comment by ykulbak** [comment]
Closed by #243
