### ISSUE TITLE
Points (pins)

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-API#236]
A very common way of marking the trouble areas, is to set pins, or points, in the 3d model. 

In the current version of BCF, you can send "Lines" in the viewpoints, but there is no support for points.
We have been discussing passing lines with the same start and end coordinate, but this is a very halfway solution. 

Instead, I suggest adding "Points".

**Comment by CBenghi** [comment]
If more than one `Pin` is used it would be useful to add a `Tag`.
This could be an optional string for each point to help reference it in the description, if needed.

**Comment by pasi-paasiala** [comment]
https://github.com/buildingSMART/BCF-XML/issues/86

**Comment by GeorgDangl** [comment]
See #284
