### ISSUE TITLE
Component: Either ifc_guid or authoring_tool_id should be required (from XML)

### ISSUE THREAD

**Issue by KevLoh** [buildingSMART/BCF-API#252]
Attribute | Optional | Description
-- | -- | --
IfcGuid | Yes, if AuthoringToolId is Provided | The IfcGuid of the component
OriginatingSystem | Yes | Name of the system in which the component is originated
AuthoringToolId | Yes, if IfcGuid is Provided | System specific identifier of the component in the originating BIM tool

Note that IfcGuid must be provided, if possible. The AuthoringToolId can be used as a fallback when an IfcGuid is not available.

**Comment by ykulbak** [comment]
Duplicate with Issue 205
