### ISSUE TITLE
Do anyone know about a free test bench solution to test the implementation of this API against?

### ISSUE THREAD

**Issue by JanErikHoel** [buildingSMART/BCF-API#266]
We will develop this API in our solution now, but need another free application or test bench to test the implementation against.
Do anyone know about such a solution?

Jan Erik Hoel
Trimble Solutions Sandvika

**Comment by GeorgDangl** [comment]
Hey @JanErikHoel, thank you for rasing that question!

We've talked about this in the conference call yesterday, but unfortunately, there's no such thing, at least that we're aware of.

There are some vendors who offer service side BCF API features, so your best bet would be to contact them: https://github.com/buildingSMART/BCF-API/wiki/November-2020-Hackathon-Implementation-Plans
