### ISSUE TITLE
Remove Authentivation and Versions

### ISSUE THREAD

**Issue by pasi-paasiala** [buildingSMART/BCF-API#267]
Authentication and Versions are redundant with [opencde-foundations](https://github.com/buildingSMART/opencde-foundation-API/tree/release_1_0/schemas).

**Comment by GeorgDangl** [comment]
Here's the folder: https://github.com/buildingSMART/BCF-API/tree/release_3_0/Schemas_draft-03/Authentication
It should be removed.

**Comment by GeorgDangl** [comment]
Also this one: https://github.com/buildingSMART/BCF-API/tree/release_3_0/Schemas_draft-03/Public
