### ISSUE TITLE
Question regarding the "file" workflow

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-API#269]
I have some comments regarding the "file" workflow, and I would appreciate your input before tomorrows hackathon.
A major blocker on BCF today, is that "wrong" models are displayed in the viewpoint.
I assume this is the motivation for adding the "file" endpoint.

I see that we have an endpoint, both for setting, and for reading "files" of a topic. There is also an endpoint that lists all possible "files" in a project.
In my mind, I think the server can only accept already present "files" in the project, not custom file information from the client.

However, this approach does not work that well in the file exchange, where the client don't know the "files" of the receiver. 

Therefore, my conclusion is that our current "file" definition in v3.0 does not work.

Am I thinking wrong about this?

**Comment by GeorgDangl** [comment]
Hey @jasollien, what do you mean with
>However, this approach does not work that well in the file exchange, where the client don't know the "files" of the receiver.

In [the project files information service](https://github.com/buildingSMART/BCF-API/tree/release_3_0#331-get-project-files-information-service), the client can get a list of files available on the server and present this to the user.

**Comment by jasollien** [comment]
> Hey @jasollien, what do you mean with
> 
> > However, this approach does not work that well in the file exchange, where the client don't know the "files" of the receiver.
> 
> In [the project files information service](https://github.com/buildingSMART/BCF-API/tree/release_3_0#331-get-project-files-information-service), the client can get a list of files available on the server and present this to the user.

Yes, it works in the API, but not in the xml. Because a BCF-file is not targeted against one specific server, it can be importer two places.

**Comment by jasollien** [comment]
https://github.com/buildingSMART/BCF-XML/pull/330
