### ISSUE TITLE
Update README to include contact details for the cde group

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/BCF-API#276]
We should have the openCDE@buildingsmart.org mail address somewhere in the document visible, ideally at the top and with a few words to explain when to reach out (not for technical support, but for getting in touch with the group).

See also https://github.com/buildingSMART/BCF-XML/issues/349 in the XML repo

**Comment by GeorgDangl** [comment]
From meeting:
* Maybe add a file like `contact.md`, same file for both repositories
* Also share schedule / info about bi-weekly meetings
* Explain that if you want to participate (get invited), send an email
* Also include hackathon dates

**Comment by ykulbak** [comment]
@GeorgDangl there are identical contributing sections in both the [BCF-XML](https://github.com/buildingSMART/BCF-XML#contributing) and the [BCF-API](https://github.com/buildingSMART/BCF-API/tree/master#contributing) specification. 

Its premature to share schedule of meetings and hackathons - as these are not regular events and are coordinated during the meetings.

Are you OK to close the issue?
