### ISSUE TITLE
Proposal: Support relating a comment to multiple viewpoints

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-API#283]
There is a need to make a comment on multiple markers/viewpoints. 

There could be 2 possible solutions.

1. Make a link in the comment text, that only would be understood by the tools supporting this.

2. Include the possibility to link multiple viewpoints to a comment in the API spec. Maybe a bit similar to "related issues" endpoint

**Comment by GeorgDangl** [comment]
We're closing this for now, but we're free to reopen if there's some more ideas and a good use case for this.

**Comment by JanErikHoel** [comment]
At least the last version of Trimble Connect commenting tool, called BCF Topics allow for multiple markers and viewpoint for one topic
