### ISSUE TITLE
Proposal: Add "status_type" to status

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-API#286]
When moving from BCF.1 to BCF 2.0 we lost the "status_type" information on statuses, because users could create custom statuses themselves. Therefore it is no longer possible to know if a topic is open or closed, except for analyzing the name of the status. This don't make sence if the status is named something different than open or closed, such as "in progress".

Knowing the meta status is very useful, if you want to create statistics, or would like to by default only display "open" topics

Therefore, we suggest adding a property called "status_type" or simular to a BCF status. 

Suggested values are: "open", "closed" (But we are open to discuss additional values, such as "candidate", etc...)

**Comment by GeorgDangl** [comment]
Note for myself, we should check the repo and the minutes, since I’m sure we talked about this some years ago.

**Comment by jasollien** [comment]
Conclusion after todays meeting.

There were some discussions whetever we should stick to two status types (open|closed) or 3 (open|accepted|closed).

- open|closed would be a better fit to todays implementations
- open|accepted|closed would probably be a better fit to the industry standards

We agreed to look more closely into this next meeting.

**Comment by GeorgDangl** [comment]
Will be covered in #327
