### ISSUE TITLE
Proposal: Add meta information to all extension types

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-API#287]
The extension schema holds the complete overview of statuses, types, priorities, labels, stages, and users if a BCF project.

However, the only information exposed is the name of these items.

For displaying this values in a client, it would make sence to add more information to every item. Also, it would make sence to have unique id's on every item, to make POST requests more API-friendly

Sugested props are
```
{
  id/guid: string (a reference that can be used instead of passing the "name"
  name: string, (same as before)
  color: optional string (A color code to display next to the item) (Maybe not that useful for users)
  icon: optional image (A small thumbnail to better visualize the item)
}
```

We are open for other values as well

**Comment by GeorgDangl** [comment]
This should also include the `status_type` from here: https://github.com/buildingSMART/BCF-API/issues/286
