### ISSUE TITLE
Proposal: Support for editing extension values

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-API#288]
Clients sees the need for updating items in the extension schema, such as statuses, types, priorities, labels, stages and users(?).

One possibility is the non interactive flow for doing this with "create/update/delete" resources.
Another possibility is the interactive flow (like we have done in the documents API), that just points the users to the server's UI

**Comment by jasollien** [comment]
Alternative solution: Expose "server url's" for viewing/updating settings/project etc...

**Comment by Amoki** [comment]
I did something similar for BIMData by adding an UPDATE route to the Extension Service. It works well and implementation is easy.
It should use permissions to not allow everyone to update Extension thought.
