### ISSUE TITLE
Proposal: Put "file" information under viewpoint instead of topic

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-API#293]
The current solution, with linking "files" to a topic is an improvement, regarding linking correct models to viewpoints. However, it is not perfect, as different viewpoint in the same topic might be showing different sets of models.

I suggest moving the "file" endpoint to pr viewpoint, instead of pr topic.

**Comment by GeorgDangl** [comment]
Needs some discussion😀

**Comment by GeorgDangl** [comment]
One alternative would be to specify the full list of IFC files in the topic, but allow each viewpoint to only reference a subset of those files.

**Comment by GeorgDangl** [comment]
We'll discuss this again in a bigger round.

**Comment by jasollien** [comment]
#319

**Comment by GeorgDangl** [comment]
That's now done by the change to how viewpoint files are referencing their parent topic files

**Comment by GeorgDangl** [comment]
In #330
