### ISSUE TITLE
Guid is duplicated in 3.2.3 GET Topic Service

### ISSUE THREAD

**Issue by vjleo** [buildingSMART/BCF-API#294]
Hi there,

GET /bcf/{version}/projects/{guid}/topics/{guid}
`https://github.com/buildingSMART/BCF-API#323-get-topic-service`
It's not good practice to have the same parameter duplicated on the endpoint.

Suggestion:
GET /bcf/{version}/projects/{project_id}/topics/{topic_guid}

**Comment by vjleo** [comment]
I have created pull request(295) for this:

https://github.com/buildingSMART/BCF-API/pull/295

**Comment by GeorgDangl** [comment]
Done via #314
