### ISSUE TITLE
Binary File Uploads

### ISSUE THREAD

**Issue by OlliSchu** [buildingSMART/BCF-API#298]
The BCF API 2.1 was stating that binary file uploads have the following header:

`Headers:
Content-Type: application/octet-stream;
Content-Length: {Size of file in bytes};
Content-Disposition: attachment; filename="{Filename.extension}";`

But in BCF 3.0 I cannot find any specifics for the binary file upload. Does this mean that there can now be different upload options per server?

**Comment by ykulbak** [comment]
Implementers of BCF API 3.0 are required to support the foundation API. Binary file uploads are defined [here](https://github.com/buildingSMART/foundation-API#19-binary-file-uploads).
