### ISSUE TITLE
Swagger: bim_snippet.is_external -> boolean or string?

### ISSUE THREAD

**Issue by phbenisc** [buildingSMART/BCF-API#303]
`bim_snippet.is_external` is `string` in [Swagger](https://app.swaggerhub.com/apis/buildingSMART/BCF/3.0#/bim_snippet),
![image](https://user-images.githubusercontent.com/5716653/168105821-829b5e35-03cb-42a5-90ea-89136b374b4f.png)

but `boolean` in the [documentation and examples](https://github.com/buildingSMART/BCF-API#322-post-topic-service).
![image](https://user-images.githubusercontent.com/5716653/168106096-e32a653e-5dd0-409f-8d1c-4e9b1ad0992c.png).

What is correct?
On an additional note the default value `false` is not in swagger.

**Comment by GeorgDangl** [comment]
Should be a boolean, but we're planning on removing the BIM Snippet in the next version, so I'm closing this😀

See this issue for the removal: https://github.com/buildingSMART/BCF-XML/issues/314
