### ISSUE TITLE
Swagger: typo document_reference_[GET, POST, PUT].desctiption instead of description

### ISSUE THREAD

**Issue by phbenisc** [buildingSMART/BCF-API#304]
Found a small typo(s) in Swagger:

![image](https://user-images.githubusercontent.com/5716653/172058944-c80cb1c3-5ced-4509-98ec-4cddd3db46a7.png)

correct naming can be found in:

- [document_reference_GET](https://github.com/buildingSMART/BCF-API/blob/release_3_0/Schemas_draft-03/Collaboration/DocumentReference/document_reference_GET.json)
- [document_reference_POST](https://github.com/buildingSMART/BCF-API/blob/release_3_0/Schemas_draft-03/Collaboration/DocumentReference/document_reference_POST.json)
- [document_reference_PUT](https://github.com/buildingSMART/BCF-API/blob/release_3_0/Schemas_draft-03/Collaboration/DocumentReference/document_reference_PUT.json)

But basically the fields are called "description".

**Comment by cosmo0** [comment]
+1
It's a real problem if, like me, you use SwaggerHub to generate your model... Thankfully I saw it but others might not, and create broken APIs.

**Comment by GeorgDangl** [comment]
Hey guys, I've fixed the Swagger documentation. Sorry for taking a bit😀 Could you check if it's all correct now?

**Comment by cosmo0** [comment]
Looks fixed, thanks.

**Comment by phbenisc** [comment]
can also confirm. Thanks @GeorgDangl !
