### ISSUE TITLE
proposal : uml class/object diagram

### ISSUE THREAD

**Issue by assaad97** [buildingSMART/BCF-API#306]
hello,

i would like to know is there a standard uml class/object diagram, like we have a standard for the bcf api routes, requests and responses, i think it would be very helpful if a spec concenrning how the database is stuctured for it to be used by the bcf api.

if there is already uml class/object diagram that is defined i would love to have a link that refers to it.

thank you.

**Comment by ykulbak** [comment]
Hi @assaad97 there is no UML class diagram available. BCF specifieshow data should be exchanged. Lower-level implementation guidance is out of the scope of this specification.
