### ISSUE TITLE
Provide overview tables of open APIs

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/BCF-API#312]
Leon asked if we can provide an overview table of all the open APIs, similar to the one for IFC: https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/

Just pinging @jasollien @pasi-paasiala @ykulbak FYI, we should discuss this in the call tomorrow.

Also, here's a first draft:

# Open APIs Overview

## Foundations API

The foundation API is a base API that provides shared features across other APIs, such as authentication, format conventions and other common features.

| Version | Published (yyyy-mm) | Status    | Documentation                                                       |
| ------- | ------------------- | --------- | ------------------------------------------------------------------- |
| 1.1     |                     | Draft     | <https://github.com/buildingSMART/foundation-API/tree/release_1_1>  |
| 1.0     | 2021-06             | Published | <https://github.com/buildingSMART/foundation-API/releases/tag/v1.0> |

## Documents API

The Documents API is designed to streamline the process of downloading and uploading files to a common data environment (CDE).

| Version | Published (yyyy-mm) | Status | Documentation                                                     |
| ------- | ------------------- | ------ | ----------------------------------------------------------------- |
| 1.0     |                     | Draft  | <https://github.com/buildingSMART/documents-API/tree/release_1_0> |

## BCF API

The BCF API allows clients and servers to exchange issue information about building models.

| Version | Published (yyyy-mm) | Status    | Documentation                                        |
| ------- | ------------------- | --------- | ---------------------------------------------------- |
| 3.0     | 2021-06             | Published | <https://github.com/buildingSMART/BCF-API/tree/v3.0> |
| 2.1     | 2017-01             | Published | <https://github.com/buildingSMART/BCF-API/tree/v2.1> |
| 1.0     | 2015-02             | Published | <https://github.com/buildingSMART/BCF-API/tree/v1.0> |

## BCF XML

BCF XML is a file based exchange format for BIM issues.

| Version | Published (yyyy-mm) | Status    | Documentation                                        |
| ------- | ------------------- | --------- | ---------------------------------------------------- |
| 3.0     | 2021-06             | Published | <https://github.com/buildingSMART/BCF-XML/tree/v3.0> |
| 2.1     | 2017-01             | Published | <https://github.com/buildingSMART/BCF-XML/tree/v2.1> |
| 2.0     | 2014-10             | Published | <https://github.com/buildingSMART/BCF-XML/tree/v2.0> |
| 1.0     | 2009                | Published |                                                      |

**Comment by berlotti** [comment]
could you put this in a markdown file somewhere in this repo?

**Comment by GeorgDangl** [comment]
Yeah, but we could also do it in a JSON file. That way, the bSI technical website could import it via the TablePress plugin, and poll it e.g. every day to be up to date.
We've just set this up a few weeks ago in the new website for the certified software table, we could do it the same way her.

**Comment by GeorgDangl** [comment]
Ok, then we'll discuss where to add it. Probably somewhere in the `main` branch of the Foundation API.

**Comment by GeorgDangl** [comment]
Closing because there's now a vendor maintained list of software at bSI: https://technical.buildingsmart.org/resources/software-implementations
