### ISSUE TITLE
Add endpoints to extract Comments and Viewpoints in batch

### ISSUE THREAD

**Issue by fernandommota** [buildingSMART/BCF-API#363]
Dear BCF-API team,

I would like to suggest two new endpoints:

- get batch comments
- get batch viewpoints

Currently, it's a requirement do requests by topic, sample:

- GET /bcf/{version}/projects/{project_id}/topics/{guid}/comments
- GET /bcf/{version}/projects/{project_id}/topics/{guid}/viewpoints

This architecture works very well for a transational perspective, but for a analytics persperctive require a request for every single topic. This can be proibitive for some cloud ETL solutions (bill by requisition). In our scenario for example, it's necessary do 120k requisitions to extract all comments from all topics for first load, by the way, we are aware of filters to create an incremental solution, but the first load it's proibitive.

So, I hope that this idea can be evaluate by the team.

Regards

**Comment by GeorgDangl** [comment]
@pasi-paasiala, we've just talked a bit about this in the call, but we need some more input from the clients perspective, there's only server vendors here today😀

We were thinking about adding parameters that would allow you to include comments and / or viewpoints when getting topics, so you could get all the topic data in one go. What do you think?

**Comment by GeorgDangl** [comment]
Hey @fernandommota, we've just discussed this in the group. At the moment, we don't plan on adding such bulk endpoints for comments or viewpoints. While it probably would work quite well for comments, viewpoints are a bit more problematic. Each viewpoint can individually be quite large if we would also include e.g. components and coloring information in them, and then such a list endpoint would have the potential of returning very big responses.
We fear it might be a bit too much effort for a very niche use case.

**Comment by fernandommota** [comment]
Dear @GeorgDangl,

I understood your point, thank you for evaluate our suggestion.

Regards
