### ISSUE TITLE
Clean up specification

### ISSUE THREAD

**Issue by GeorgDangl** [BuildingSMART/BCF-API#47]
Currently there are a few things that could be improved in the specification:

- [x] Fix indenting in all Json examples to a consistent style (i.e. replace /t with spaces and have a fixed count of spaces per indention level)
- [x] Change all tables from embedded Html to Markdown tables
- [x] General Cleanup like trailing whitespaces at line ends and trailing hashtags for headers

**Comment by nicktindall** [comment]
#29 has a lot of whitespace normalization in it (point 1) I also corrected some broken hashtag links

**Comment by GeorgDangl** [comment]
See #58
