### ISSUE TITLE
Odata filter is restricted by url-limit.

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/BCF-API#50]
We have decided to use [odata](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/) as standard for filtering our requests. However, as earlier pointed out. Odata is not very charachter-effective when it comes to filtering, especially when filtering by lists. 

Solutions:
1. The BCF-group suggested soluting was to support odata in POST request.

Hovewer, according to the odata standard this is not a supported feature. Possible solution is to pass the entire filter string in a post form, but I don't think this is good practice.

2.Support longer URL's. I came across this [post](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers). There is possible to increase the max URL-limit on the server side, but the clients being used may have it's own limitation.

Conclusion. I was hoping for odata post filter support, but regarding our options, I would still go for solution 1, because it would be the least bad practice.

**Comment by ykulbak** [comment]
+1

**Comment by GeorgDangl** [comment]
Decided to keep as-is (URL Parameter) in 2.1 and switch to POST Body in 3.0 when there are problems in real usages

**Comment by GeorgDangl** [comment]
There hasn't been a problem in 7 years😀
