### ISSUE TITLE
Response codes and contents for POST/PUT requests should be clearly specified

### ISSUE THREAD

**Issue by ykulbak** [BuildingSMART/BCF-API#52]
The specification is ambiguous around HTTP status codes and responses a BCF client should expect. for example: https://github.com/BuildingSMART/BCF-API#422-post-topic-services only specifies request headers and body but there is no reference to expected responses.

**Comment by GeorgDangl** [comment]
Hi @ykulbak,

could you please review #59 to check if it's fulfilling all needs for this issue?

**Comment by GeorgDangl** [comment]
Handled by #63
