### ISSUE TITLE
"document_guid" Property to Document References

### ISSUE THREAD

**Issue by linhard** [buildingSMART/BCF-API#53]
document_reference objects can either be stored externally (then they are being referenced by their 
resource url pointing to that document) or stored on the server as project document, then they are being referenced by their document_guid.
This has been rejected at Bratislava Hackathon but needs to further discussed.

**Comment by jasollien** [comment]
This once again needs attention.

In order to create a document reference to an internal document, there must be a document_guid attribute on DocumentReferenceGET, DocumentReferencePOST and DocumentReferencePUT

**Comment by jasollien** [comment]
I have made a pull request for this: https://github.com/BuildingSMART/BCF-API/pull/140
