### ISSUE TITLE
Section 3.2.5 / dynRegClient_POST.json schema specifies string max lengths -> Unnecessary

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/BCF-API#57]
The schema for creating a dynamic OAuth2 client (as well as the table in the documentation) specify max lengths for the client_name and client_description strings.
This is not specified elsewhere in the API and I don't see the need to have such arbitrary length restrictions in the API itself.
If there are implementation limits, the server should return proper error codes.

(Raised this for completeness, since as far as I remember we'll be ditching that process altogether in favor of anonymous clients)

**Comment by linhard** [comment]
Agreed for v2.1

**Comment by jasollien** [comment]
👍

**Comment by ykulbak** [comment]
Move to foundations API

**Comment by ykulbak** [comment]
To be addressed in the release of the foundations API

**Comment by ykulbak** [comment]
Migrated to the [Foundation API](https://github.com/buildingSMART/shared-common-API/issues/4)
