### ISSUE TITLE
Releases of the API should be tagged

### ISSUE THREAD

**Issue by nicktindall** [BuildingSMART/BCF-API#65]
The repository doesn't have tags on revisions to allow readers to go back and look at previous versions of the documentation for a particular release.
I've been looking at the documentation to try and fix our implementation of v1 of the API but there's no tags that I can go back to to see what the API looked like at version 1. The accepted revision (the one that was submitted to building smart) for each version of the API should be tagged with the version number. Or some similar strategy adopted.

**Comment by GeorgDangl** [comment]
The initial version of the API was released in February 2015, and that's the last commit I found from then: 434efcf1c32b02d962d8ede981524ef930a985f9

We should use Mondays telecon to find out which one to tag as 1.0 release, since we somehow didn't keep track of that=)
