### ISSUE TITLE
Not all resources have guids

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/BCF-API#66]
Regarding the issue 87 [Custom identifiers for files in the topics header](https://github.com/BuildingSMART/BCF-XML/pull/87) in BCF XML, it was discovered that we don't have guids for all resource types.

This makes some operations, like changing a certain file element  ([see Specification](https://github.com/BuildingSMART/BCF-API#432-put-files-header-service)) not possible.

This issue is opened so that a decision on how to proceed (introduce guids to all elements?) can be made during the review process before the final release of v2.1 in October.

**Comment by ykulbak** [comment]
Closed by the above pull request
