### ISSUE TITLE
Lists variable names should be in plural

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-API#72]
Example:

"bitmap" is the name of an array of "Bitmap". It should be named "bitmaps".

This issue appends to:
bitmaps
lines
clippingPlanes

**Comment by GeorgDangl** [comment]
I very much agree with you, and since we've already had the same discussion in BCF XML (which was accepted), I'll just make the change without further discussion=)

**Comment by GeorgDangl** [comment]
Would you take a look at #76 and see if that's fixing it?
