### ISSUE TITLE
Components resource in BCF-api 2.1 does not reflect the new component data structure in BCF-xml 2.1

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-API#85]
In BCF-xml the components are separated in 4 lists.

In the api it is still that "one" resource for the main list.

How to solve?

1: Add a "componentType" attribute on each component and add odata filtering on componentType.

2: Create 4 resources, one for each component type

I would recommend option 1.

**Comment by GeorgDangl** [comment]
I also favor your first option. This would imho better resemble an inheritance or type relation and not indicate that there are, in fact, four totally different kinds of components. I'll try to get a PR by tomorrow.

**Comment by GeorgDangl** [comment]
I guess this is fixed with the latest changes to the Viewpoint Components?
