### ISSUE TITLE
Should viewpoint components be immutable?

### ISSUE THREAD

**Issue by jasollien** [BuildingSMART/BCF-API#86]
From our point of view it might be useful being able to update the components in the viewpoint. How is this affected by saying viewpoints are immutable?

Suggestions:
1. Keep it as it is. Make it possible to update the components on the viewpoint

2. Remove Components PUT and add Components POST. 

Any thougts?

**Comment by GeorgDangl** [comment]
I just renamed the Components PUT to POST and removed the Viewpoint Authorization Actions.

Viewpoint Components shouldn't change when Viewpoints aren't allowed to, I did just overlook it when doing the change to viewpoints yesterday=)

See 650404ced1f1a8c027f1e24c24c5faafee48673e, 5f7c903d070396693d3ec9f27999e043168157a1 and 356dae2ae993faf828d50011099d06aa469846af
