### ISSUE TITLE
Comment status listed as an odata filter parameter

### ISSUE THREAD

**Issue by nicktindall** [BuildingSMART/BCF-API#89]
In the get comments section https://github.com/BuildingSMART/BCF-API#441-get-comments-service, "status" is listed as an ODAta filter parameter, but nowhere else does comment status seem to exist, it's not the in the get or put comment schema. I think it was removed for 2.1?

**Comment by jasollien** [comment]
@GeorgDangl @nicktindall. Fixed here: https://github.com/BuildingSMART/BCF-API/pull/109
