### ISSUE TITLE
What to do when OAuth is not supported by the server?

### ISSUE THREAD

**Issue by nicktindall** [BuildingSMART/BCF-API#91]
In 2.1 the auth info endpoint has all the oauth2_* parameters as mandatory, does this mean if OAuth2 is not available for that particular server that we return blank strings for those fields? omitting them would  be against the schema.

**Comment by GeorgDangl** [comment]
Make properties for OAuth2 optional

**Comment by GeorgDangl** [comment]
Fixed in cb91621
